
const constants = {
  /* User constants */
  ADD_USER: 'ADD_USER',
  EDIT_USER: 'EDIT_USER',
  REMOVE_USER: 'REMOVE_USER',
  /* Board constants */
  ADD_BOARD: 'ADD_BOARD',
  /* Column constants */
  ADD_COLUMN: 'ADD_COLUMN',
  EDIT_COLUMN_TITLE: 'EDIT_COLUMN_TITLE',
  /* Card constants */
  ADD_CARD: 'ADD_CARD',
  ADD_CARD_DESCRIPTION: 'ADD_CARD_DESCRIPTION',
  EDIT_CARD_NAME: 'EDIT_CARD_NAME',
  EDIT_CARD_DESCRIPTION: 'EDIT_CARD_DESCRIPTION',
  REMOVE_CARD: 'REMOVE_CARD',
  /* Comment constants */
  ADD_COMMENT: 'ADD_COMMENT',
  EDIT_COMMENT: 'EDIT_COMMENT',
  REMOVE_COMMENT: 'REMOVE_COMMENT',
  SET_COMMENT_EDIT_MODE: 'SET_COMMENT_EDIT_MODE',
  REMOVE_COMMENT_BY_CARD_ID: 'REMOVE_COMMENT_BY_CARD_ID',
  RESET_COMMENT_EDIT_MODE: 'RESET_COMMENT_EDIT_MODE'
}

export default constants;